# -*- coding: utf-8 -*-
"""Försäkringsbolag på den svenska bilförsäkringsmarknaden.

VAD SOM ÄR VERIFIERAT OCH VAD SOM INTE ÄR DET
  'ski'      Svenskt Kvalitetsindex 2025, branschmätningen för bilförsäkring.
             Skala 0–100. Bolag utan tillräcklig marknadsandel saknar värde.
  'kons'     Konsumenternas Försäkringsbyrå, betyg 1–5 på villkoren.
  'fakta'    Uppgifter från bolagens egna publicerade villkor.
  'pris'     PLATSHÅLLARE. Ersätt med egen insamling före lansering.

Varje bolag har egen rubrikuppsättning och egen sektionsordning, så att de
femton sidorna inte delar skelett. Se README.
"""

BOLAG = [

{
 'slug': 'folksam', 'namn': 'Folksam', 'kort': 'Folksam',
 'ski': 75.2, 'kons': 4.6, 'kons_produkt': 'Bilförsäkring Stor',
 'typ': 'Kundägt', 'grundat': 1908,
 'sammanfattning': 'Sveriges största bilförsäkringsbolag mätt i antal försäkrade fordon. '
   'Bilförsäkring Stor fick 4,6 av 5 av Konsumenternas Försäkringsbyrå — det högsta betyget '
   'på marknaden — och bolaget är kundägt, vilket innebär att överskottet stannar hos '
   'försäkringstagarna i stället för hos aktieägare.',
 'fakta': [('Fyra nivåer', 'Trafik, bilförsäkring, bilförsäkring med vagnskada och Stor Bilförsäkring'),
           ('Samlingsrabatt', '10 procent vid hemförsäkring i samma bolag, mer vid flera bilar'),
           ('Självriskreducering', 'Vid djurkollision och skadegörelse i Stor Bilförsäkring'),
           ('Kundägt', 'Inga externa aktieägare')],
 'passar': ['Dig som vill ha marknadens högst betygsatta villkor',
            'Hushåll som kan samla hem och bil för rabatt',
            'Dig som kör i områden med mycket vilt'],
 'passar_ej': ['Dig som enbart jagar lägsta möjliga premie',
               'Dig med en gammal bil där trafikförsäkring räcker',
               'Dig som vill sköta allt i en app'],
 'vinkel': 'storlek',
 'h2': {'pris': 'Vad kostar Folksam bilförsäkring?',
        'villkor': 'Fyra nivåer — men bara en heter Stor',
        'betyg': 'Höst betyg av alla på Konsumenternas skala',
        'passar': 'Vem är Folksam byggt för?',
        'byta': 'Så säger du upp din Folksam-försäkring',
        'skada': 'Anmäla skada hos Folksam'},
 'ordning': ['pris', 'betyg', 'villkor', 'passar', 'skada', 'byta'],
},

{
 'slug': 'lansforsakringar', 'namn': 'Länsförsäkringar', 'kort': 'Länsförsäkringar',
 'ski': 77.9, 'kons': 4.5, 'kons_produkt': 'med alla tillägg',
 'typ': '23 självständiga länsbolag', 'grundat': 1801,
 'sammanfattning': 'Inte ett bolag utan tjugotre. Länsförsäkringar består av självständiga, '
   'kundägda länsbolag med egna priser och egna villkor. Det betyder att din premie beror på '
   'vilket län du bor i — och att en generell prisjämförelse för hela landet inte är möjlig.',
 'fakta': [('23 bolag', 'Varje länsbolag sätter egna priser och villkor'),
           ('Kundägt', 'Länsbolagen ägs av sina försäkringstagare'),
           ('SKI 77,9', 'Mycket nöjda kunder i 2025 års mätning'),
           ('Konsumenternas 4,5', 'Med samtliga tillägg valda')],
 'passar': ['Dig som vill ha lokal förankring och personlig kontakt',
            'Dig som redan har bank eller andra försäkringar i huset',
            'Dig som värdesätter villkorens innehåll högre än priset'],
 'passar_ej': ['Dig som vill kunna jämföra ett nationellt pris',
               'Dig som flyttar ofta mellan län',
               'Dig som helst sköter allt digitalt utan kontakt'],
 'vinkel': 'struktur',
 'h2': {'pris': 'Varför Länsförsäkringar inte har ett pris',
        'villkor': 'Vad tjugotre bolag betyder i praktiken',
        'betyg': 'Betyg och kundnöjdhet',
        'passar': 'Passar Länsförsäkringar dig?',
        'byta': 'Uppsägning — och varför länet spelar roll',
        'skada': 'Skadeanmälan går via ditt länsbolag'},
 'ordning': ['villkor', 'pris', 'betyg', 'passar', 'byta', 'skada'],
},

{
 'slug': 'if', 'namn': 'If Skadeförsäkring', 'kort': 'If',
 'ski': 72, 'kons': None, 'kons_produkt': None,
 'typ': 'Del av Sampo', 'grundat': 1999,
 'sammanfattning': 'Nordens största sakförsäkringsbolag. Styrkan ligger i skadehanteringen — '
   'i Konsumenternas mätning 2025 låg handläggningstiden för enklare skador på i snitt fyra '
   'arbetsdagar, bland de lägsta i branschen. Priset ligger sällan i botten.',
 'fakta': [('Nordens största', 'Verksamhet i Sverige, Norge, Danmark och Finland'),
           ('4 arbetsdagar', 'Snitthandläggning för enklare skador, Konsumenternas 2025'),
           ('SKI 72', 'Nöjda kunder — under snittet bland de stora'),
           ('Kombinationsrabatt', 'Vid flera försäkringar i samma bolag')],
 'passar': ['Dig som prioriterar snabb skadehantering',
            'Dig som redan har hem- eller reseförsäkring hos If',
            'Dig som kör i flera nordiska länder'],
 'passar_ej': ['Dig som söker lägsta premie',
               'Dig med äldre bil där grundskyddet räcker',
               'Dig som inte samlar fler försäkringar'],
 'vinkel': 'skada',
 'h2': {'pris': 'Vad kostar If bilförsäkring?',
        'villkor': 'Brett utbud av tillägg',
        'betyg': 'Fyra dagar — det If är bäst på',
        'passar': 'När är If värt priset?',
        'byta': 'Byta från If',
        'skada': 'Skadehanteringen steg för steg'},
 'ordning': ['betyg', 'pris', 'skada', 'villkor', 'passar', 'byta'],
},

{
 'slug': 'trygg-hansa', 'namn': 'Trygg-Hansa', 'kort': 'Trygg-Hansa',
 'ski': 71, 'kons': None, 'kons_produkt': None,
 'typ': 'Del av Intact Financial', 'grundat': 1899,
 'sammanfattning': 'Ett av de mest välkända varumärkena på svensk försäkringsmarknad, med '
   'livbojen som symbol sedan decennier. I SKI:s mätning 2025 landade bolaget på 71 — nöjda '
   'kunder, men lägst bland de stora aktörerna.',
 'fakta': [('Grundat 1899', 'Ett av Sveriges äldsta försäkringsbolag'),
           ('SKI 71', 'Lägst bland de stora bolagen i 2025 års mätning'),
           ('Brett produktutbud', 'Bil, hem, olycksfall och företag'),
           ('Del av Intact', 'Kanadensiskägt sedan 2021')],
 'passar': ['Dig som vill ha ett stort och etablerat bolag',
            'Dig som samlar flera försäkringar',
            'Dig som föredrar telefon framför app'],
 'passar_ej': ['Dig som styr efter kundnöjdhetsmätningar',
               'Dig som söker lägsta premie',
               'Dig som vill ha allt digitalt'],
 'vinkel': 'etablerad',
 'h2': {'pris': 'Vad kostar Trygg-Hansa bilförsäkring?',
        'villkor': 'Vad som ingår i de tre nivåerna',
        'betyg': 'Kundnöjdhet — siffran som sticker ut',
        'passar': 'Vem passar Trygg-Hansa för?',
        'byta': 'Säga upp Trygg-Hansa',
        'skada': 'Om du råkar ut för en skada'},
 'ordning': ['pris', 'villkor', 'passar', 'betyg', 'skada', 'byta'],
},

{
 'slug': 'gjensidige', 'namn': 'Gjensidige', 'kort': 'Gjensidige',
 'ski': None, 'kons': 4.5, 'kons_produkt': 'Bilförsäkring Plus',
 'typ': 'Norskt, noterat', 'grundat': 1816,
 'sammanfattning': 'Nordens tredje största försäkringsbolag med omkring 2,5 miljoner '
   'försäkrade bilar. Bilförsäkring Plus fick 4,5 av 5 av Konsumenternas Försäkringsbyrå, och '
   'maskinskadeskyddet är ett av marknadens mest generösa: det gäller tills bilen är tio år '
   'eller har körts 12 000 mil.',
 'fakta': [('2,5 miljoner bilar', 'Försäkrade i Norden'),
           ('Maskinskada 10 år', 'Eller 12 000 mil — längre än de flesta'),
           ('Allrisk ingår', 'I både hel- och halvförsäkring'),
           ('Konsumenternas 4,5', 'För Bilförsäkring Plus')],
 'passar': ['Dig med en bil som passerat åtta år men inte tio',
            'Dig som vill ha allrisk utan att betala extra',
            'Dig som kör mycket i Europa'],
 'passar_ej': ['Dig som vill ha ett svenskt bolag med lokala kontor',
               'Dig som tycker att paket och tillägg blir förvirrande',
               'Dig med en bil värd under 30 000 kronor'],
 'vinkel': 'villkor',
 'h2': {'pris': 'Vad kostar Gjensidige bilförsäkring?',
        'villkor': 'Maskinskada i tio år — det som skiljer',
        'betyg': 'Betyg 4,5 av Konsumenternas',
        'passar': 'När är Gjensidige rätt val?',
        'byta': 'Uppsägning och byte',
        'skada': 'Skadeanmälan hos Gjensidige'},
 'ordning': ['villkor', 'betyg', 'pris', 'passar', 'byta', 'skada'],
},

{
 'slug': 'dina-forsakringar', 'namn': 'Dina Försäkringar', 'kort': 'Dina',
 'ski': 80.2, 'kons': None, 'kons_produkt': None,
 'typ': 'Federation av lokala bolag', 'grundat': 1990,
 'sammanfattning': 'Vinnaren i SKI:s kundnöjdhetsmätning 2025 med 80,2 poäng — högst av '
   'samtliga bilförsäkringsbolag. Dina är en federation av lokala, kundägda bolag och '
   'försäkrar över 374 000 fordon.',
 'fakta': [('SKI 80,2', 'Högsta kundnöjdheten på marknaden 2025'),
           ('374 000 fordon', 'Försäkrade i Sverige'),
           ('Lokalt ägande', 'Federation av självständiga bolag'),
           ('Personlig kontakt', 'Lokala kontor snarare än callcenter')],
 'passar': ['Dig som värdesätter service högre än lägsta pris',
            'Dig som vill ha en lokal kontakt vid skada',
            'Dig utanför storstadsregionerna'],
 'passar_ej': ['Dig som jagar absolut lägsta premie',
               'Dig som vill sköta allt i en app',
               'Dig som vill ha ett rikstäckande enhetligt pris'],
 'vinkel': 'kundnojdhet',
 'h2': {'pris': 'Vad kostar Dina Försäkringar?',
        'villkor': 'Skyddet i korthet',
        'betyg': 'Marknadens nöjdaste kunder',
        'passar': 'Passar Dina dig?',
        'byta': 'Byta till eller från Dina',
        'skada': 'Skadeärenden och lokal handläggning'},
 'ordning': ['betyg', 'passar', 'pris', 'villkor', 'skada', 'byta'],
},

{
 'slug': 'hedvig', 'namn': 'Hedvig', 'kort': 'Hedvig',
 'ski': None, 'kons': None, 'kons_produkt': None,
 'typ': 'Digital utmanare', 'grundat': 2017,
 'sammanfattning': 'Digital utmanare utan bindningstid. Det som skiljer Hedvig mest från '
   'marknaden är att bolaget inte tar ut förhöjd självrisk för förare under 25 år — något '
   'som annars är standard och som gör unga bilister dyra att försäkra.',
 'fakta': [('Ingen åldersstraff', 'Ingen förhöjd självrisk för förare under 25'),
           ('Ingen bindningstid', 'Du kan säga upp när som helst'),
           ('Stenskott utan självrisk', 'Vid lagning på hel- och halvförsäkring'),
           ('Fritt verkstadsval', 'Bilen lämnas på valfri verkstad')],
 'passar': ['Unga förare under 25 — här är prisskillnaden störst',
            'Dig som vill kunna säga upp när som helst',
            'Dig som föredrar app framför telefonkö'],
 'passar_ej': ['Dig som vill ha ett kontor att gå till',
               'Dig med veteranbil eller ovanliga behov',
               'Dig som vill ha allrisk i grundskyddet — det är tillägg'],
 'vinkel': 'utmanare',
 'h2': {'pris': 'Vad kostar Hedvig bilförsäkring?',
        'villkor': 'Tre valbara tillägg — och vad som redan ingår',
        'betyg': 'En ny aktör utan SKI-data',
        'passar': 'Hedvig är byggt för en viss typ av bilägare',
        'byta': 'Ingen bindningstid — så säger du upp',
        'skada': 'Skadeanmälan i appen'},
 'ordning': ['passar', 'pris', 'villkor', 'byta', 'skada', 'betyg'],
},

{
 'slug': 'ica-forsakring', 'namn': 'ICA Försäkring', 'kort': 'ICA',
 'ski': None, 'kons': None, 'kons_produkt': None,
 'typ': 'Del av ICA-gruppen', 'grundat': 2005,
 'sammanfattning': 'Har vuxit till en av de större aktörerna. Det som sticker ut är att '
   'allrisk — drulleförsäkring — ingår som standard i både halv- och helförsäkring, medan de '
   'flesta konkurrenter tar extra betalt för det.',
 'fakta': [('Allrisk ingår', 'Standard i både halv- och helförsäkring'),
           ('Fast pris i 5 år', 'För nya, skadefria kunder'),
           ('Stammisrabatt', 'Extra rabatt för ICA-kunder'),
           ('Maskinskada 8 år', 'Eller 12 000 mil')],
 'passar': ['Dig som redan handlar på ICA',
            'Dig som vill ha allrisk utan tillägg',
            'Dig som vill kunna planera kostnaden långsiktigt'],
 'passar_ej': ['Dig som inte är ICA-kund och inte tänker bli det',
               'Dig med bil äldre än åtta år som vill ha maskinskydd',
               'Dig som söker absolut lägsta premie'],
 'vinkel': 'medlem',
 'h2': {'pris': 'Vad kostar ICA bilförsäkring?',
        'villkor': 'Allrisk som standard — det ovanliga',
        'betyg': 'Omdömen och kundnöjdhet',
        'passar': 'När lönar sig ICA Försäkring?',
        'byta': 'Uppsägning och stammisrabatt',
        'skada': 'Vid skada'},
 'ordning': ['villkor', 'pris', 'passar', 'skada', 'byta', 'betyg'],
},

{
 'slug': 'svedea', 'namn': 'Svedea', 'kort': 'Svedea',
 'ski': 79.9, 'kons': None, 'kons_produkt': None,
 'typ': 'Nischbolag', 'grundat': 2011,
 'sammanfattning': 'Näst högsta kundnöjdheten i SKI 2025 med 79,9 poäng. Bolaget har en '
   'viktig begränsning som få jämförelsesajter nämner: bilförsäkringen tecknas inte i '
   'Stockholm, Göteborg och Malmö.',
 'fakta': [('SKI 79,9', 'Näst högst av alla bilförsäkringsbolag 2025'),
           ('Ej i storstad', 'Tecknas inte i Stockholm, Göteborg eller Malmö'),
           ('0 kr självrisk trafik', 'Ingen grundsjälvrisk vid trafikskada'),
           ('Allrisk ingår', 'I både hel- och halvförsäkring')],
 'passar': ['Dig som bor utanför de tre storstadsregionerna',
            'Dig som vill ha fritt verkstadsval',
            'Dig som prioriterar kundnöjdhet'],
 'passar_ej': ['Dig som bor i Stockholm, Göteborg eller Malmö — du kan inte teckna',
               'Dig som vill kunna byta mitt i året',
               'Dig som vill ha ett stort bolag med brett produktutbud'],
 'vinkel': 'nisch',
 'h2': {'pris': 'Vad kostar Svedea bilförsäkring?',
        'villkor': 'Vad som ingår — och var du kan teckna',
        'betyg': 'Näst nöjdaste kunderna i landet',
        'passar': 'Bor du i storstad kan du hoppa över Svedea',
        'byta': 'Bindningstid och uppsägning',
        'skada': 'Fritt verkstadsval vid skada'},
 'ordning': ['passar', 'betyg', 'pris', 'villkor', 'skada', 'byta'],
},

{
 'slug': 'gofido', 'namn': 'Gofido', 'kort': 'Gofido',
 'ski': None, 'kons': 4.1, 'kons_produkt': 'stor försäkring',
 'typ': 'Digital utmanare', 'grundat': 2010,
 'sammanfattning': 'Digital aktör som fick 4,1 av 5 för sin stora bilförsäkring hos '
   'Konsumenternas Försäkringsbyrå. Styrkan är valfriheten — du kan justera tillägg och '
   'självrisknivå mer än hos många konkurrenter.',
 'fakta': [('Konsumenternas 4,1', 'För den stora försäkringen'),
           ('Hög anpassningsbarhet', 'Justerbara tillägg och självrisknivåer'),
           ('Digitalt', 'Tecknas och sköts online'),
           ('Konkurrenskraftig premie', 'Låga omkostnader ger lägre pris')],
 'passar': ['Dig som vill skruva på självrisk och tillägg själv',
            'Elbilsägare som vill anpassa skyddet',
            'Dig som är bekväm med att sköta allt digitalt'],
 'passar_ej': ['Dig som vill ha en färdig standardlösning',
               'Dig som vill ringa och prata med en rådgivare',
               'Dig som vill ha ett stort etablerat varumärke'],
 'vinkel': 'flexibel',
 'h2': {'pris': 'Vad kostar Gofido bilförsäkring?',
        'villkor': 'Bygg skyddet själv',
        'betyg': '4,1 av 5 hos Konsumenternas',
        'passar': 'Vem passar Gofido?',
        'byta': 'Uppsägning',
        'skada': 'Skadeanmälan digitalt'},
 'ordning': ['villkor', 'passar', 'betyg', 'pris', 'byta', 'skada'],
},

{
 'slug': 'moderna-forsakringar', 'namn': 'Moderna Försäkringar', 'kort': 'Moderna',
 'ski': None, 'kons': None, 'kons_produkt': None,
 'typ': 'Del av Tryg', 'grundat': 1997,
 'sammanfattning': 'Ingår i den nordiska Tryg-koncernen. Ett medelstort bolag som ligger i '
   'mittfältet på både pris och villkor, och som ofta dyker upp som ett rimligt alternativ '
   'utan att sticka ut åt något håll.',
 'fakta': [('Del av Tryg', 'Nordisk koncern'),
           ('Bilsport & MC', 'Nischvarumärke för entusiastfordon'),
           ('Medelstort', 'Etablerat men inte bland de största'),
           ('Brett utbud', 'Bil, hem, båt och företag')],
 'passar': ['Dig som vill ha ett mellanalternativ utan ytterligheter',
            'Dig som redan har andra försäkringar i koncernen',
            'Ägare av entusiastfordon via Bilsport & MC'],
 'passar_ej': ['Dig som söker lägsta premie',
               'Dig som styr efter oberoende betyg — data saknas',
               'Dig som vill ha lokala kontor'],
 'vinkel': 'mitten',
 'h2': {'pris': 'Vad kostar Moderna bilförsäkring?',
        'villkor': 'Skyddets omfattning',
        'betyg': 'Begränsad oberoende data',
        'passar': 'Var passar Moderna in?',
        'byta': 'Byta bolag',
        'skada': 'Skadehantering'},
 'ordning': ['pris', 'villkor', 'passar', 'skada', 'betyg', 'byta'],
},

{
 'slug': 'paydrive', 'namn': 'Paydrive', 'kort': 'Paydrive',
 'ski': None, 'kons': 4.2, 'kons_produkt': 'grundprodukt',
 'typ': 'Beteendebaserat', 'grundat': 2013,
 'sammanfattning': 'Premien sätts efter hur du faktiskt kör. En dosa eller app mäter '
   'körstil, och den som kör försiktigt betalar mindre. Paydrive delar förstaplatsen bland '
   'grundprodukterna hos Konsumenternas med 4,2 poäng.',
 'fakta': [('Konsumenternas 4,2', 'Delad förstaplats bland grundprodukterna'),
           ('Körstil styr priset', 'Mätning via app eller dosa'),
           ('Belönar försiktighet', 'Lugn körstil ger lägre premie'),
           ('Kräver mätning', 'Du måste acceptera att körningen registreras')],
 'passar': ['Dig som kör lugnt och vill betala för det',
            'Unga förare som vill bevisa sin körstil',
            'Dig som kör lite och förutsägbart'],
 'passar_ej': ['Dig som inte vill bli mätt',
               'Dig som kör sportigt eller mycket i mörker',
               'Dig som vill ha ett fast, förutsägbart pris']  ,
 'vinkel': 'telematik',
 'h2': {'pris': 'Hur Paydrive sätter ditt pris',
        'villkor': 'Vad mätningen registrerar',
        'betyg': 'Delad förstaplats hos Konsumenternas',
        'passar': 'Paydrive passar inte alla',
        'byta': 'Uppsägning och utrustning',
        'skada': 'Skada — och hur körstilsdata används'},
 'ordning': ['pris', 'villkor', 'passar', 'betyg', 'skada', 'byta'],
},

{
 'slug': 'watercircles', 'namn': 'Watercircles', 'kort': 'Watercircles',
 'ski': None, 'kons': 4.2, 'kons_produkt': 'grundprodukt',
 'typ': 'Nordiskt nischbolag', 'grundat': 2015,
 'sammanfattning': 'Mindre nordisk aktör som delar förstaplatsen bland grundprodukterna hos '
   'Konsumenternas Försäkringsbyrå med 4,2 poäng — i sällskap med Länsförsäkringar och '
   'Paydrive. Ett litet bolag med villkor i toppklass.',
 'fakta': [('Konsumenternas 4,2', 'Delad förstaplats bland grundprodukterna'),
           ('Nordiskt', 'Verksamhet i flera nordiska länder'),
           ('Miljöprofil', 'Marknadsför sig mot miljömedvetna kunder'),
           ('Litet bolag', 'Begränsat produktutbud')],
 'passar': ['Dig som vill ha starka grundvillkor utan tillägg',
            'Dig som föredrar mindre aktörer',
            'Elbils- och hybridägare'],
 'passar_ej': ['Dig som vill ha ett brett produktutbud att samla',
               'Dig som vill ha lokala kontor',
               'Dig som styr efter kundnöjdhetsmätningar — data saknas'],
 'vinkel': 'villkor',
 'h2': {'pris': 'Vad kostar Watercircles?',
        'villkor': 'Starka grundvillkor',
        'betyg': 'I toppen bland grundprodukterna',
        'passar': 'Vem är Watercircles för?',
        'byta': 'Byta till Watercircles',
        'skada': 'Skadehantering hos en mindre aktör'},
 'ordning': ['betyg', 'villkor', 'pris', 'passar', 'byta', 'skada'],
},

{
 'slug': 'volvia', 'namn': 'Volvia', 'kort': 'Volvia',
 'ski': 75.8, 'kons': None, 'kons_produkt': None,
 'typ': 'Del av If', 'grundat': 1959,
 'sammanfattning': 'Volvos egen försäkring, som i praktiken drivs av If. Fördelen är att '
   'skyddet är byggt kring Volvo och Volvos verkstadsnät. Nackdelen är att du sällan får '
   'marknadens lägsta pris.',
 'fakta': [('Del av If', 'Drivs av Nordens största sakförsäkringsbolag'),
           ('SKI 75,8', 'Mycket nöjda kunder 2025'),
           ('Volvo-anpassat', 'Originaldelar och auktoriserade verkstäder'),
           ('Gäller Volvo', 'Tecknas till Volvo-bilar')],
 'passar': ['Dig med en nyare Volvo under garanti',
            'Dig som vill ha originaldelar vid reparation',
            'Dig som köpt bilen hos en Volvo-handlare'],
 'passar_ej': ['Dig med en äldre Volvo där märkesverkstad inte är avgörande',
               'Dig som söker lägsta premie',
               'Dig med annat bilmärke'],
 'vinkel': 'marke',
 'h2': {'pris': 'Vad kostar Volvia?',
        'villkor': 'Byggt kring Volvo',
        'betyg': 'Kundnöjdhet 75,8',
        'passar': 'När är Volvia värt det?',
        'byta': 'Byta från Volvia till ett fristående bolag',
        'skada': 'Skada och auktoriserad verkstad'},
 'ordning': ['villkor', 'passar', 'pris', 'betyg', 'skada', 'byta'],
},

{
 'slug': 'aktsam', 'namn': 'Aktsam', 'kort': 'Aktsam',
 'ski': None, 'kons': 4.2, 'kons_produkt': 'stor försäkring',
 'typ': 'Nischbolag', 'grundat': 2009,
 'sammanfattning': 'Mindre aktör som fick 4,2 av 5 för sin stora bilförsäkring hos '
   'Konsumenternas Försäkringsbyrå — högst bland de nyare bolagen i den kategorin.',
 'fakta': [('Konsumenternas 4,2', 'För den stora försäkringen'),
           ('Nyare aktör', 'En av utmanarna på marknaden'),
           ('Fokus på fordon', 'Specialiserat produktutbud'),
           ('Digitalt', 'Tecknas och sköts online')],
 'passar': ['Dig som vill ha starka villkor från en mindre aktör',
            'Dig som jämför på innehåll snarare än varumärke',
            'Dig som är bekväm digitalt'],
 'passar_ej': ['Dig som vill ha lokala kontor',
               'Dig som vill samla många försäkringar',
               'Dig som styr efter kundnöjdhetsdata — den saknas'],
 'vinkel': 'utmanare',
 'h2': {'pris': 'Vad kostar Aktsam bilförsäkring?',
        'villkor': 'Den stora försäkringens innehåll',
        'betyg': '4,2 av 5 hos Konsumenternas',
        'passar': 'Vem bör titta på Aktsam?',
        'byta': 'Uppsägning',
        'skada': 'Skadeanmälan'},
 'ordning': ['betyg', 'pris', 'villkor', 'passar', 'skada', 'byta'],
},

{
 'slug': 'evoli', 'namn': 'Evoli', 'kort': 'Evoli',
 'ski': None, 'kons': None, 'kons_produkt': None,
 'typ': 'Digital utmanare', 'grundat': 2018,
 'sammanfattning': 'Helt appbaserat bolag. Allt — tecknande, ändringar och skadeanmälan — '
   'sker i appen. Passar den som aldrig vill ringa, och passar inte den som vill kunna det.',
 'fakta': [('Appbaserat', 'Allt hanteras digitalt'),
           ('Ung aktör', 'Grundat 2018'),
           ('Låga omkostnader', 'Ingen kontorsstruktur'),
           ('Begränsat utbud', 'Färre produkter att samla')],
 'passar': ['Dig som vill sköta allt i mobilen',
            'Dig som byter försäkring digitalt och ofta',
            'Dig som prioriterar enkelhet före bredd'],
 'passar_ej': ['Dig som vill kunna ringa en person',
               'Dig med ovanliga fordon eller behov',
               'Dig som vill samla flera försäkringstyper'],
 'vinkel': 'digital',
 'h2': {'pris': 'Vad kostar Evoli?',
        'villkor': 'Vad som ingår',
        'betyg': 'Ingen oberoende data ännu',
        'passar': 'Evoli är byggt för mobilen',
        'byta': 'Byta till eller från Evoli',
        'skada': 'Skadeanmälan i appen'},
 'ordning': ['passar', 'villkor', 'pris', 'skada', 'byta', 'betyg'],
},
]
